title: <p align="center"> Bimsara Pathiraja </p>

logo: "/images/picture2.png?raw=true"

description:
  <p align="center">
  <a href="pdf/cv.pdf">CV</a> |
  <a href="https://www.linkedin.com/in/bimsara-pathiraja-2536a913b/">LinkedIn</a> |
  <a href="https://github.com/bimsarapathiraja">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing BSc. (Hons) degree in Engineering at the University of Moratuwa, Sri Lanka.
  <br><br>
Before joining ASU, I worked as a Research Assistant at Mohamed bin Zayed University of Artificial Intelligence (MBZUAI), UAE, under Dr. Muhammad Haris Khan. I earned a BSc (Hons) in Electronic and Telecommunication Engineering from the University of Moratuwa, Sri Lanka, graduating with First-Class Honors.
  <br><br>
  In my free time, I enjoy reading non-fiction (you can find my current list at the bottom), cooking, playing chess, badminton, and swimming.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
