title: <p align="center"> Bimsara Pathiraja </p>

logo: "/images/picture2.png?raw=true"

description:
  <p align="center">
  <a href="pdf/cv.pdf">CV</a> |
  <a href="https://www.linkedin.com/in/bimsara-pathiraja-2536a913b/">LinkedIn</a> |
  <a href="https://github.com/bimsarapathiraja">GitHub</a>
  </p>
  
  <p align="justify">
  I am pursing BSc. (Hons) degree in Engineering at the University of Moratuwa, Sri Lanka.
  <br><br>
  I am currently a part-time Machine Learning Engineer at <a href='https://www.promiseq.com/'>PromiseQ</a>.
  <br><br>
  My main interests are computer vision, autonomous systems and 3d deep learning.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
