etitle: <p align="center"> Bimsara Pathiraja2 </p>

logo: "/images/picture2.png?raw=true"

description:
  <p align="center">
  <a href="pdf/summer-internship-resume-bim-2025.pdf">Resume</a> |
  <a href="https://x.com/bimsarap1">X</a> |
  <a href="https://github.com/bimsarapathiraja">GitHub</a>
  </p>
  
  <p align="justify">
  Hi! I am a second-year Computer Science PhD student at ASU, advised by Prof. Chitta Baral. My research focuses on enhancing the reasoning capabilities of multi-modal models and large language models, with expertise in text-to-image diffusion models, flow models, image editing, and LLM reasoning.
  <br><br>
  Before joining ASU, I worked as a Research Assistant at Mohamed bin Zayed University of Artificial Intelligence (MBZUAI), UAE, under Dr. Muhammad Haris Khan. I earned a BSc (Hons) in Electronic and Telecommunication Engineering from the University of Moratuwa, Sri Lanka, graduating with First-Class Honors.
  <br><br>
  In my free time, I enjoy reading non-fiction (you can find my current list at the bottom), cooking, playing chess, badminton, and swimming.
  </p>
  
theme: jekyll-theme-minimal
google_analytics: UA-145578661-1 # Google Analytics tracking ID
